package example

import (
	"context"
	"go.opentelemetry.io/otel"
	otelCodes "go.opentelemetry.io/otel/codes"
)

//instrument:include Bark

type Dog struct{}

func (s Dog) Bark(ctx context.Context) (name string, errInstrument error) {
	ctx, span := otel.Tracer("app").Start(ctx, "Dog.Bark")
	defer span.End()
	defer func() {
		if errInstrument != nil {
			span.SetStatus(otelCodes.Error, "error")
			span.RecordError(errInstrument)
		}
	}()

	return "spot", nil
}

type Racoon struct{}

func (s Racoon) Shh(ctx context.Context, a int) (err error) {
	return nil
}
