package example

import (
	"context"
	"go.opentelemetry.io/otel"
	otelCodes "go.opentelemetry.io/otel/codes"
)

type ContextHolder struct {
	ctx context.Context
}

// Should be instrumented - context in receiver only
func (c ContextHolder) MethodWithoutContextParam() (err error) {
	c.ctx, span := otel.Tracer("app").Start(c.ctx, "ContextHolder.MethodWithoutContextParam")
	defer span.End()
	defer func() {
		if err != nil {
			span.SetStatus(otelCodes.Error, "error")
			span.RecordError(err)
		}
	}()

	return nil
}

// Should be skipped - context in both receiver and params
func (c ContextHolder) MethodWithContextParam(ctx context.Context) (err error) {
	return nil
}

// Another structure to test
type MultiContextReceiver struct {
	ctx1 context.Context
	ctx2 context.Context
}

// Should not be instrumented - has multiple context in receiver
func (m MultiContextReceiver) MethodWithReceiverContext() (err error) {
	return nil
}