// Code generated by asdf DO NOT EDIT

package example

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

func Skip3(ctx context.Context) (name string, err error) {
	ctx, span := otel.Tracer("app").Start(ctx, "Skip3")
	defer span.End()
	defer func() {
		if err != nil {
			span.SetStatus(codes.Error, "error")
			span.RecordError(err)
		}
	}()

	return "asdf", nil
}
