// Code generated by stringer -type Pill pill.go; DO NOT EDIT.

package example

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

func Skip3(ctx context.Context) (name string, err error) {
	return "asdf", nil
}
