package example

import (
	"context"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

type Dog struct{}

func (s Dog) Bark(ctx context.Context) (name string, err error) {
	ctx, span := otel.Tracer("app").Start(ctx, "Dog.Bark")
	defer span.End()
	defer func() {
		if err != nil {
			span.SetStatus(codes.Error, "error")
			span.RecordError(err)
		}
	}()
	return "spot", nil
}

type Racoon struct{}

func (s Racoon) Shh(ctx context.Context, a int) (err error) {
	return nil
}
